version: '3.7'
services:
  mongo_db:
    image: mongo
    ports:
    - '27017:27017'
    restart: always
  postgre:
    image: postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/gymtablesAPI
      - /gymtablesAPI/node_modules
    ports:
    - '5000:5000'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/gymtablesClient
      - /gymtablesClient/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development