version: '3.7'
services:
  mongo_db:
    image: mongo
    ports:
    - '27017:27017'
    restart: always
  postgre:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/gymtablesAPI
      - /gymtablesAPI/node_modules
    ports:
    - '5000:5000'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/gymtablesClient
      - /gymtablesClient/node_modules
      - ./conf.d:/etc/nginx/conf.d/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NODE_ENV=development
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email bso080601@gmail.com --agree-tos --no-eff-email -d ociofy.es
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt