version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo_db:
    image: mongo
    ports:
    - '27017:27017'
    restart: always
  api:
    build:
      context: ./server-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./server-api:/gymtablesAPI
      - /gymtablesAPI/node_modules
    ports:
    - '4000:4000'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/gymtablesClient
      - /gymtablesClient/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  postgres: ~

